version: "3.8"

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
